language: python

python:
  - "3.6"

cache:
  pip:
  apt:
  directories:
    - .tox

env:
  - TOXENV=py27-django18-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
  - TOXENV=py27-django18-imagemagick APT=imagemagick
  - TOXENV=py27-django18-graphicsmagick APT=graphicsmagick
  - TOXENV=py27-django18-redis
  - TOXENV=py27-django18-wand
  - TOXENV=py27-django18-pgmagick APT='libgraphicsmagick++1-dev libboost-python-dev'
  - TOXENV=py27-django18-dbm
  - TOXENV=py34-django18-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
  - TOXENV=py34-django18-imagemagick APT=imagemagick
  - TOXENV=py34-django18-graphicsmagick APT=graphicsmagick
  - TOXENV=py34-django18-redis
  - TOXENV=py34-django18-wand
  - TOXENV=py34-django18-dbm
  - TOXENV=py35-django110-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
  - TOXENV=py35-django110-imagemagick APT=imagemagick
  - TOXENV=py35-django110-graphicsmagick APT=graphicsmagick
  - TOXENV=py35-django110-redis
  - TOXENV=py35-django110-wand
  - TOXENV=py35-django110-dbm
  - TOXENV=py36-django111-pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
  - TOXENV=py36-django111-imagemagick APT=imagemagick
  - TOXENV=py36-django111-graphicsmagick APT=graphicsmagick
  - TOXENV=py36-django111-redis
  - TOXENV=py36-django111-wand
  - TOXENV=py36-django111-dbm


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq $APT

after_failure:
  - cat /home/travis/.pip/pip.log

after_success: coveralls

install:
  - pip install -q flake8 tox coveralls

script:
  - env | sort
  - tox
  - flake8 --show-source sorl/

services:
  - redis-server

notifications:
  email: false

deploy:
  provider: pypi
  user: jazzband
  distributions: sdist bdist_wheel
  password:
    secure: VD+63Tnv0VYNfFQv9f1KZ0k79HSX8veNk4dTy42Hriteci50z5uSQdZMnqqD83xQJa4VF6N7DHkxHnBVOWLCqGQZeYqR/5BuDFNUewcr6O14dk31HvxMsWDaN1KW0Qwtus8ZrztwGhZtZ/92ODA6luHI4mCTzqX0gcG0/aKd75s=
  on:
    tags: true
    repo: jazzband/sorl-thumbnail
